services:
  mongo:
    image: initialized-mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: phonebook_backend
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  server:
    depends_on:
      mongo:
        condition: service_healthy
    image: phonebook-backend
    ports:
      - 3001:3001
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: phonebook-backend
    environment:
      - MONGO_URL=mongodb://root:example@mongo:27017/phonebook_backend
      - REDIS_URL=redis://redis:6379
      - DEBUG=phonebook-express-backend:*
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  app:
    image: phonebook-front
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: phonebook-front
    depends_on:
      - server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - server
      - app
