services:
  mongo:
    image: initialized-mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: todo_backend
    volumes:
      - ./mongo_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - 6370:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes: 
      - ./redis_data:/data
      
volumes:
  mongo_data:
  redis_data: